### ISSUE TITLE
I got a error

### ISSUE THREAD

**Issue by Dysfunctional89** [ozankaraali/PiTV#3]
When I tried to add new server info (url and mac) I got this error
`(node:2927) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://<server url>/server/load.php?type=stb&action=handshake reason: Unexpected token < in JSON at position 0
    at /home/dys/PiTV/out/PiTV-linux-x64/resources/app/.webpack/main/index.js:24260:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/dys/PiTV/out/PiTV-linux-x64/resources/app/.webpack/main/index.js:24990:21
(node:2927) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 62)
(node:2927) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2927) UnhandledPromiseRejectionWarning: FetchError: invalid json response body at http://nextv.bossna-caffe.com:25461/c/server/load.php?type=stb&action=handshake reason: Unexpected token < in JSON at position 0
    at /home/dys/PiTV/out/PiTV-linux-x64/resources/app/.webpack/main/index.js:24260:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/dys/PiTV/out/PiTV-linux-x64/resources/app/.webpack/main/index.js:24990:21
(node:2927) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 64)
`

**Comment by ozankaraali** [comment]
Thank you for posting the issue, I will try to reproduce that error as soon as possible. I think it is a server-specific error, but when I try, I will write you back.

**Comment by Dysfunctional89** [comment]
Thanks for quick answer, I don't think it's a server-specific error, every server I tested works on android.

**Comment by ozankaraali** [comment]
I understand, while I was testing I haven’t encountered any errors like this and my friends also tested on different servers. But you might be right, since it’s an early-stage program, I will check back and try to fix it. Thank you.

**Comment by Dysfunctional89** [comment]
Any way, good luck, I'm a linux user over 10 years, me and a lot of users would like to have app like this, alternative to SF-VIP Player (for Windows), and STB emu (Android).

**Comment by ozankaraali** [comment]
@Dysfunctional89 sorry for the late response but I found out that you put server address as http://<server_addr:port>/c/, which you should just write the part http://example.com:1234, nothing else. No "/c/" is needed

**Comment by ozankaraali** [comment]
Sorry for the late response, I was busy a bit. 
I think this error happens due to the server response, since it resolves to <unexpected end of JSON input> and you were able to play the first channel you clicked. Have you tried to do a <reload>, it renews the tokens to the server. Probably you have figured it out after so many days (again, sorry for the late response 😅 )

**Comment by ozankaraali** [comment]
I am closing this issue due to inactivity, if the problem still persists, reopen it.
