### ISSUE TITLE
Deb package not working

### ISSUE THREAD

**Issue by faveoled** [ozankaraali/PiTV#5]
Running Ubuntu 20.04
```
user@hp-laptop:~$ pitv
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EPERM: operation not permitted, chmod '/usr/lib/pitv/resources/app/.webpack/main/native_modules/ffmpeg'
    at Object.chmodSync (fs.js:1209:3)
    at Module.<anonymous> (/usr/lib/pitv/resources/app/.webpack/main/index.js:334:27579)
    at n (/usr/lib/pitv/resources/app/.webpack/main/index.js:1:124)
    at Object.<anonymous> (/usr/lib/pitv/resources/app/.webpack/main/index.js:168:34845)
    at n (/usr/lib/pitv/resources/app/.webpack/main/index.js:1:124)
    at /usr/lib/pitv/resources/app/.webpack/main/index.js:1:957
    at Object.<anonymous> (/usr/lib/pitv/resources/app/.webpack/main/index.js:1:968)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
```

**Comment by ozankaraali** [comment]
As it shows in the error report, your user somehow cannot change the user rights of the file
/usr/lib/pitv/resources/app/.webpack/main/native_modules/ffmpeg
Which is needed the program to run.
Maybe try with superuser access, or chmod this file manually.
Also, in Linux, if I remember correctly, you even could use your own ffmpeg but you might need to compile it from the source with removing ffmpeg prebuilt packages.

**Comment by faveoled** [comment]
I ran this and it worked:
```
sudo chown user /usr/lib/pitv/resources/app/.webpack/main/native_modules/ffmpeg
```
Thanks.
